[package]
name = "sudoku"
version = "0.1.0"
authors = ["haennes <hannes.hofmuth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug_print = "^1"

[[bin]]
name = "sudoku"
path = "src/main.rs"
